# Generated by Django 4.1.7 on 2023-03-26 11:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_bookingsessions_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingtuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuitiontype', models.CharField(choices=[('GCSE Biology', 'GCSE Biology'), ('GCSE Chemistry', 'GCSE Chemistry'), ('GCSE Physics', 'GCSE Physics'), ('A-LEVEL Biology', 'A-LEVEL Biology'), ('A-LEVEL Chemistry', 'A-LEVEL Chemistry'), ('A-LEVEL Physics', 'A-LEVEL Physics')], default='GCSE Biology', max_length=75)),
                ('day', models.DateField(verbose_name=datetime.datetime.now)),
                ('time_choice', models.CharField(choices=[('4-5 PM', '4-5 PM'), ('5-6 PM', '5-6 PM'), ('6-7 PM', '6-7 PM'), ('7-8 PM', '7-8 PM'), ('8-9 PM', '8-9 PM')], default='4-5 PM', max_length=6)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='bookingsessions',
        ),
    ]
